remote_theme: pmarsceill/just-the-docs
title: About Maksymilian Kwapi≈Ñski
description: Academic and Interests Background

# Enable Just the Docs navigation
just_the_docs:
  show_nav: true     # Enables the sidebar navigation automatically
  nav_order: 1       # Sets order of navigation items
  search_enabled: true  # Enable search in the navigation

